// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add.sql

package db

import (
	"context"
)

const add = `-- name: Add :exec
INSERT INTO records (id, kind, updated_at_unix, payload)
VALUES (?, ?, ?, ?)
`

type AddParams struct {
	ID            string
	Kind          int64
	UpdatedAtUnix int64
	Payload       []byte
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.ExecContext(ctx, add,
		arg.ID,
		arg.Kind,
		arg.UpdatedAtUnix,
		arg.Payload,
	)
	return err
}
