// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package db

import (
	"context"
)

const get = `-- name: Get :many
SELECT id, kind, payload
FROM records
`

type GetRow struct {
	ID      string
	Kind    int64
	Payload []byte
}

func (q *Queries) Get(ctx context.Context) ([]GetRow, error) {
	rows, err := q.db.QueryContext(ctx, get)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRow
	for rows.Next() {
		var i GetRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
