// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
)

const enqueueOutbox = `-- name: EnqueueOutbox :exec
INSERT INTO outbox (operation_id, record_id, kind, updated_at_unix, payload, created_at_unix)
VALUES (?, ?, ?, ?, ?, ?)
`

type EnqueueOutboxParams struct {
	OperationID   string
	RecordID      string
	Kind          int64
	UpdatedAtUnix int64
	Payload       []byte
	CreatedAtUnix int64
}

func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutbox,
		arg.OperationID,
		arg.RecordID,
		arg.Kind,
		arg.UpdatedAtUnix,
		arg.Payload,
		arg.CreatedAtUnix,
	)
	return err
}
