// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package db

import (
	"context"
)

const addRecord = `-- name: AddRecord :exec
INSERT INTO records (id, kind, updated_at_unix, payload)
VALUES (?, ?, ?, ?)
`

type AddRecordParams struct {
	ID            string
	Kind          int64
	UpdatedAtUnix int64
	Payload       []byte
}

func (q *Queries) AddRecord(ctx context.Context, arg AddRecordParams) error {
	_, err := q.db.ExecContext(ctx, addRecord,
		arg.ID,
		arg.Kind,
		arg.UpdatedAtUnix,
		arg.Payload,
	)
	return err
}

const getRecords = `-- name: GetRecords :many
SELECT id, kind, payload
FROM records
`

type GetRecordsRow struct {
	ID      string
	Kind    int64
	Payload []byte
}

func (q *Queries) GetRecords(ctx context.Context) ([]GetRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecordsRow
	for rows.Next() {
		var i GetRecordsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
