// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const add = `-- name: Add :exec
INSERT INTO
    challenges (user_id, id, device_name, challenge, expires_at)
VALUES ($1, $2, $3, $4 ,$5)
`

type AddParams struct {
	UserID     uuid.UUID
	ID         uuid.UUID
	DeviceName string
	Challenge  []byte
	ExpiresAt  time.Time
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add,
		arg.UserID,
		arg.ID,
		arg.DeviceName,
		arg.Challenge,
		arg.ExpiresAt,
	)
	return err
}
