// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failure.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updateWithFailure = `-- name: UpdateWithFailure :exec
UPDATE challenges
SET attempts = attempts + 1
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) UpdateWithFailure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateWithFailure, id)
	return err
}
