// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: success.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updateWithSuccess = `-- name: UpdateWithSuccess :exec
UPDATE challenges
SET used_at = now()
WHERE id = $1
`

func (q *Queries) UpdateWithSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateWithSuccess, id)
	return err
}
