// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const add = `-- name: Add :exec
INSERT INTO users (id, username) VALUES ($1, $2)
`

type AddParams struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add, arg.ID, arg.Username)
	return err
}
