// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const get = `-- name: Get :many
SELECT id, username FROM users
`

type GetRow struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) Get(ctx context.Context) ([]GetRow, error) {
	rows, err := q.db.Query(ctx, get)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRow
	for rows.Next() {
		var i GetRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
