// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getChanges = `-- name: GetChanges :many
SELECT j.server_seq, j.id, j.kind, j.updated_at_unix, j.payload, j.operation_id
FROM journal j
JOIN users u
    ON u.id = j.user_id
WHERE u.username = $1
  AND j.server_seq > $2
ORDER BY j.server_seq
LIMIT $3
`

type GetChangesParams struct {
	Username  string
	ServerSeq int64
	Limit     int32
}

type GetChangesRow struct {
	ServerSeq     int64
	ID            uuid.UUID
	Kind          int32
	UpdatedAtUnix int64
	Payload       []byte
	OperationID   uuid.UUID
}

func (q *Queries) GetChanges(ctx context.Context, arg GetChangesParams) ([]GetChangesRow, error) {
	rows, err := q.db.Query(ctx, getChanges, arg.Username, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChangesRow
	for rows.Next() {
		var i GetChangesRow
		if err := rows.Scan(
			&i.ServerSeq,
			&i.ID,
			&i.Kind,
			&i.UpdatedAtUnix,
			&i.Payload,
			&i.OperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
