// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getChanges = `-- name: GetChanges :many
SELECT j.server_seq, j.id, j.kind, j.updated_at_unix, j.payload, j.operation_id
FROM journal j
JOIN users u
    ON u.id = j.user_id
WHERE u.username = $1
  AND j.server_seq > $2
ORDER BY j.server_seq
LIMIT $3
`

type GetChangesParams struct {
	Username  string
	ServerSeq int64
	Limit     int32
}

type GetChangesRow struct {
	ServerSeq     int64
	ID            uuid.UUID
	Kind          int32
	UpdatedAtUnix int64
	Payload       []byte
	OperationID   uuid.UUID
}

func (q *Queries) GetChanges(ctx context.Context, arg GetChangesParams) ([]GetChangesRow, error) {
	rows, err := q.db.Query(ctx, getChanges, arg.Username, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChangesRow
	for rows.Next() {
		var i GetChangesRow
		if err := rows.Scan(
			&i.ServerSeq,
			&i.ID,
			&i.Kind,
			&i.UpdatedAtUnix,
			&i.Payload,
			&i.OperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChange = `-- name: InsertChange :exec
WITH u AS (
    SELECT id FROM users WHERE username = $1
)
INSERT INTO journal(user_id, id, kind, updated_at_unix, payload, operation_id)
SELECT u.id, $2, $3, $4, $5, $6
FROM u
ON CONFLICT (user_id, operation_id) DO NOTHING
`

type InsertChangeParams struct {
	Username      string
	ID            uuid.UUID
	Kind          int32
	UpdatedAtUnix int64
	Payload       []byte
	OperationID   uuid.UUID
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) error {
	_, err := q.db.Exec(ctx, insertChange,
		arg.Username,
		arg.ID,
		arg.Kind,
		arg.UpdatedAtUnix,
		arg.Payload,
		arg.OperationID,
	)
	return err
}
