// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
)

const deleteOutbox = `-- name: DeleteOutbox :exec
DELETE FROM outbox WHERE operation_id = ?
`

func (q *Queries) DeleteOutbox(ctx context.Context, operationID string) error {
	_, err := q.db.ExecContext(ctx, deleteOutbox, operationID)
	return err
}

const listOutboxBatch = `-- name: ListOutboxBatch :many
SELECT operation_id, record_id, kind, updated_at_unix, payload
FROM outbox
ORDER BY created_at_unix
LIMIT ?
`

type ListOutboxBatchRow struct {
	OperationID   string
	RecordID      string
	Kind          int64
	UpdatedAtUnix int64
	Payload       []byte
}

func (q *Queries) ListOutboxBatch(ctx context.Context, limit int64) ([]ListOutboxBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboxBatchRow
	for rows.Next() {
		var i ListOutboxBatchRow
		if err := rows.Scan(
			&i.OperationID,
			&i.RecordID,
			&i.Kind,
			&i.UpdatedAtUnix,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
