// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package db

import (
	"context"
)

const upsertRecord = `-- name: UpsertRecord :exec
INSERT INTO records (id, kind, updated_at_unix, payload)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind            = excluded.kind,
    updated_at_unix = excluded.updated_at_unix,
    payload         = excluded.payload
`

type UpsertRecordParams struct {
	ID            string
	Kind          int64
	UpdatedAtUnix int64
	Payload       []byte
}

func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecord,
		arg.ID,
		arg.Kind,
		arg.UpdatedAtUnix,
		arg.Payload,
	)
	return err
}
