// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_state.sql

package db

import (
	"context"
)

const getCursor = `-- name: GetCursor :one
SELECT last_server_seq FROM sync_state WHERE id = 1
`

func (q *Queries) GetCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCursor)
	var last_server_seq int64
	err := row.Scan(&last_server_seq)
	return last_server_seq, err
}

const setCursor = `-- name: SetCursor :exec
UPDATE sync_state SET last_server_seq = ? WHERE id = 1
`

func (q *Queries) SetCursor(ctx context.Context, lastServerSeq int64) error {
	_, err := q.db.ExecContext(ctx, setCursor, lastServerSeq)
	return err
}
