// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.1
// source: sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushStatus int32

const (
	PushStatus_PUSH_STATUS_UNSPECIFIED PushStatus = 0
	PushStatus_APPLIED                 PushStatus = 1
	PushStatus_STALE                   PushStatus = 2 // server has a newer version
	PushStatus_CONFLICT                PushStatus = 3 // server has this version, but with different content
	PushStatus_DUPLICATE               PushStatus = 4 // the record was already processed
)

// Enum value maps for PushStatus.
var (
	PushStatus_name = map[int32]string{
		0: "PUSH_STATUS_UNSPECIFIED",
		1: "APPLIED",
		2: "STALE",
		3: "CONFLICT",
		4: "DUPLICATE",
	}
	PushStatus_value = map[string]int32{
		"PUSH_STATUS_UNSPECIFIED": 0,
		"APPLIED":                 1,
		"STALE":                   2,
		"CONFLICT":                3,
		"DUPLICATE":               4,
	}
)

func (x PushStatus) Enum() *PushStatus {
	p := new(PushStatus)
	*p = x
	return p
}

func (x PushStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[0].Descriptor()
}

func (PushStatus) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[0]
}

func (x PushStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushStatus.Descriptor instead.
func (PushStatus) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

type RecordChange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordId        string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`                           // UUID
	Version         int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                            // +1 on every local change
	Deleted         bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`                                            // record is deleted
	Nonce           []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                 // AES-GCM nonce (12 bytes)
	Ciphertext      []byte                 `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                                       // encrypted data
	Tag             []byte                 `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`                                                     // AES-GCM authentication tag (16 bytes)
	UpdatedAtUnixMs int64                  `protobuf:"varint,7,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"` // Last-Write-Wins
	OperationId     string                 `protobuf:"bytes,8,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                  // UUID (idempotency)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordChange) Reset() {
	*x = RecordChange{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordChange) ProtoMessage() {}

func (x *RecordChange) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordChange.ProtoReflect.Descriptor instead.
func (*RecordChange) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *RecordChange) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *RecordChange) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecordChange) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *RecordChange) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *RecordChange) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *RecordChange) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *RecordChange) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *RecordChange) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // server_seq
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *PullRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *PullRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*ChangeEnvelope      `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *PullResponse) GetChanges() []*ChangeEnvelope {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *PullResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *PullResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ChangeEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // server_seq
	Change        *RecordChange          `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEnvelope) Reset() {
	*x = ChangeEnvelope{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEnvelope) ProtoMessage() {}

func (x *ChangeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEnvelope.ProtoReflect.Descriptor instead.
func (*ChangeEnvelope) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeEnvelope) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ChangeEnvelope) GetChange() *RecordChange {
	if x != nil {
		return x.Change
	}
	return nil
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*RecordChange        `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *PushRequest) GetChanges() []*RecordChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PushResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *PushResponse) GetResults() []*PushResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PushResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Status        PushStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=gophkeeper.v1.PushStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResult) Reset() {
	*x = PushResult{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResult) ProtoMessage() {}

func (x *PushResult) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResult.ProtoReflect.Descriptor instead.
func (*PushResult) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *PushResult) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *PushResult) GetStatus() PushStatus {
	if x != nil {
		return x.Status
	}
	return PushStatus_PUSH_STATUS_UNSPECIFIED
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\rgophkeeper.v1\"\xf7\x01\n" +
	"\fRecordChange\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x05 \x01(\fR\n" +
	"ciphertext\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\fR\x03tag\x12+\n" +
	"\x12updated_at_unix_ms\x18\a \x01(\x03R\x0fupdatedAtUnixMs\x12!\n" +
	"\foperation_id\x18\b \x01(\tR\voperationId\";\n" +
	"\vPullRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\fPullResponse\x127\n" +
	"\achanges\x18\x01 \x03(\v2\x1d.gophkeeper.v1.ChangeEnvelopeR\achanges\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"]\n" +
	"\x0eChangeEnvelope\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x123\n" +
	"\x06change\x18\x02 \x01(\v2\x1b.gophkeeper.v1.RecordChangeR\x06change\"D\n" +
	"\vPushRequest\x125\n" +
	"\achanges\x18\x01 \x03(\v2\x1b.gophkeeper.v1.RecordChangeR\achanges\"C\n" +
	"\fPushResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.gophkeeper.v1.PushResultR\aresults\"\\\n" +
	"\n" +
	"PushResult\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.PushStatusR\x06status*^\n" +
	"\n" +
	"PushStatus\x12\x1b\n" +
	"\x17PUSH_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aAPPLIED\x10\x01\x12\t\n" +
	"\x05STALE\x10\x02\x12\f\n" +
	"\bCONFLICT\x10\x03\x12\r\n" +
	"\tDUPLICATE\x10\x042\x8f\x01\n" +
	"\vSyncService\x12?\n" +
	"\x04Pull\x12\x1a.gophkeeper.v1.PullRequest\x1a\x1b.gophkeeper.v1.PullResponse\x12?\n" +
	"\x04Push\x12\x1a.gophkeeper.v1.PushRequest\x1a\x1b.gophkeeper.v1.PushResponseB\x1aZ\x18gophkeeper/pkg/grpc/syncb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sync_proto_goTypes = []any{
	(PushStatus)(0),        // 0: gophkeeper.v1.PushStatus
	(*RecordChange)(nil),   // 1: gophkeeper.v1.RecordChange
	(*PullRequest)(nil),    // 2: gophkeeper.v1.PullRequest
	(*PullResponse)(nil),   // 3: gophkeeper.v1.PullResponse
	(*ChangeEnvelope)(nil), // 4: gophkeeper.v1.ChangeEnvelope
	(*PushRequest)(nil),    // 5: gophkeeper.v1.PushRequest
	(*PushResponse)(nil),   // 6: gophkeeper.v1.PushResponse
	(*PushResult)(nil),     // 7: gophkeeper.v1.PushResult
}
var file_sync_proto_depIdxs = []int32{
	4, // 0: gophkeeper.v1.PullResponse.changes:type_name -> gophkeeper.v1.ChangeEnvelope
	1, // 1: gophkeeper.v1.ChangeEnvelope.change:type_name -> gophkeeper.v1.RecordChange
	1, // 2: gophkeeper.v1.PushRequest.changes:type_name -> gophkeeper.v1.RecordChange
	7, // 3: gophkeeper.v1.PushResponse.results:type_name -> gophkeeper.v1.PushResult
	0, // 4: gophkeeper.v1.PushResult.status:type_name -> gophkeeper.v1.PushStatus
	2, // 5: gophkeeper.v1.SyncService.Pull:input_type -> gophkeeper.v1.PullRequest
	5, // 6: gophkeeper.v1.SyncService.Push:input_type -> gophkeeper.v1.PushRequest
	3, // 7: gophkeeper.v1.SyncService.Pull:output_type -> gophkeeper.v1.PullResponse
	6, // 8: gophkeeper.v1.SyncService.Push:output_type -> gophkeeper.v1.PushResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		EnumInfos:         file_sync_proto_enumTypes,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
