// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.1
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KdfAlg int32

const (
	KdfAlg_KDF_ALG_UNSPECIFIED KdfAlg = 0
	KdfAlg_ARGON2ID            KdfAlg = 1
)

// Enum value maps for KdfAlg.
var (
	KdfAlg_name = map[int32]string{
		0: "KDF_ALG_UNSPECIFIED",
		1: "ARGON2ID",
	}
	KdfAlg_value = map[string]int32{
		"KDF_ALG_UNSPECIFIED": 0,
		"ARGON2ID":            1,
	}
)

func (x KdfAlg) Enum() *KdfAlg {
	p := new(KdfAlg)
	*p = x
	return p
}

func (x KdfAlg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KdfAlg) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[0].Descriptor()
}

func (KdfAlg) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[0]
}

func (x KdfAlg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KdfAlg.Descriptor instead.
func (KdfAlg) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type AuthKeyAlg int32

const (
	AuthKeyAlg_AUTH_KEY_ALG_UNSPECIFIED AuthKeyAlg = 0
	AuthKeyAlg_HMAC_SHA256              AuthKeyAlg = 1
	AuthKeyAlg_HMAC_SHA512              AuthKeyAlg = 2
)

// Enum value maps for AuthKeyAlg.
var (
	AuthKeyAlg_name = map[int32]string{
		0: "AUTH_KEY_ALG_UNSPECIFIED",
		1: "HMAC_SHA256",
		2: "HMAC_SHA512",
	}
	AuthKeyAlg_value = map[string]int32{
		"AUTH_KEY_ALG_UNSPECIFIED": 0,
		"HMAC_SHA256":              1,
		"HMAC_SHA512":              2,
	}
)

func (x AuthKeyAlg) Enum() *AuthKeyAlg {
	p := new(AuthKeyAlg)
	*p = x
	return p
}

func (x AuthKeyAlg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthKeyAlg) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[1].Descriptor()
}

func (AuthKeyAlg) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[1]
}

func (x AuthKeyAlg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthKeyAlg.Descriptor instead.
func (AuthKeyAlg) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

type KdfParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alg           KdfAlg                 `protobuf:"varint,1,opt,name=alg,proto3,enum=gophkeeper.v1.KdfAlg" json:"alg,omitempty"`
	TimeCost      uint32                 `protobuf:"varint,2,opt,name=time_cost,json=timeCost,proto3" json:"time_cost,omitempty"`
	MemoryCost    uint32                 `protobuf:"varint,3,opt,name=memory_cost,json=memoryCost,proto3" json:"memory_cost,omitempty"`
	Parallelism   uint32                 `protobuf:"varint,4,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	Salt          []byte                 `protobuf:"bytes,5,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KdfParams) Reset() {
	*x = KdfParams{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KdfParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KdfParams) ProtoMessage() {}

func (x *KdfParams) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KdfParams.ProtoReflect.Descriptor instead.
func (*KdfParams) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *KdfParams) GetAlg() KdfAlg {
	if x != nil {
		return x.Alg
	}
	return KdfAlg_KDF_ALG_UNSPECIFIED
}

func (x *KdfParams) GetTimeCost() uint32 {
	if x != nil {
		return x.TimeCost
	}
	return 0
}

func (x *KdfParams) GetMemoryCost() uint32 {
	if x != nil {
		return x.MemoryCost
	}
	return 0
}

func (x *KdfParams) GetParallelism() uint32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

func (x *KdfParams) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Kdf              *KdfParams             `protobuf:"bytes,2,opt,name=kdf,proto3" json:"kdf,omitempty"`
	EncryptedDataKey []byte                 `protobuf:"bytes,3,opt,name=encrypted_data_key,json=encryptedDataKey,proto3" json:"encrypted_data_key,omitempty"` // EDK = Enc(MasterKey, DataKey)
	AuthKey          []byte                 `protobuf:"bytes,4,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`                              // HKDF(DataKey, "auth")
	AuthKeyAlg       AuthKeyAlg             `protobuf:"varint,5,opt,name=auth_key_alg,json=authKeyAlg,proto3,enum=gophkeeper.v1.AuthKeyAlg" json:"auth_key_alg,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetKdf() *KdfParams {
	if x != nil {
		return x.Kdf
	}
	return nil
}

func (x *RegisterRequest) GetEncryptedDataKey() []byte {
	if x != nil {
		return x.EncryptedDataKey
	}
	return nil
}

func (x *RegisterRequest) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

func (x *RegisterRequest) GetAuthKeyAlg() AuthKeyAlg {
	if x != nil {
		return x.AuthKeyAlg
	}
	return AuthKeyAlg_AUTH_KEY_ALG_UNSPECIFIED
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

type LoginStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStartRequest) Reset() {
	*x = LoginStartRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStartRequest) ProtoMessage() {}

func (x *LoginStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStartRequest.ProtoReflect.Descriptor instead.
func (*LoginStartRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginStartRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginStartRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type LoginStartResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Kdf              *KdfParams             `protobuf:"bytes,2,opt,name=kdf,proto3" json:"kdf,omitempty"`
	EncryptedDataKey []byte                 `protobuf:"bytes,3,opt,name=encrypted_data_key,json=encryptedDataKey,proto3" json:"encrypted_data_key,omitempty"`              // need to client to get DataKey
	AuthKeyAlg       AuthKeyAlg             `protobuf:"varint,4,opt,name=auth_key_alg,json=authKeyAlg,proto3,enum=gophkeeper.v1.AuthKeyAlg" json:"auth_key_alg,omitempty"` // reminder to client how to calculate
	Challenge        []byte                 `protobuf:"bytes,5,opt,name=challenge,proto3" json:"challenge,omitempty"`                                                      // one-time challenge
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginStartResponse) Reset() {
	*x = LoginStartResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStartResponse) ProtoMessage() {}

func (x *LoginStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStartResponse.ProtoReflect.Descriptor instead.
func (*LoginStartResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginStartResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginStartResponse) GetKdf() *KdfParams {
	if x != nil {
		return x.Kdf
	}
	return nil
}

func (x *LoginStartResponse) GetEncryptedDataKey() []byte {
	if x != nil {
		return x.EncryptedDataKey
	}
	return nil
}

func (x *LoginStartResponse) GetAuthKeyAlg() AuthKeyAlg {
	if x != nil {
		return x.AuthKeyAlg
	}
	return AuthKeyAlg_AUTH_KEY_ALG_UNSPECIFIED
}

func (x *LoginStartResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type LoginFinishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Response      []byte                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"` // HMAC(DataKey, challenge)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFinishRequest) Reset() {
	*x = LoginFinishRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFinishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFinishRequest) ProtoMessage() {}

func (x *LoginFinishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFinishRequest.ProtoReflect.Descriptor instead.
func (*LoginFinishRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginFinishRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginFinishRequest) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type LoginFinishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFinishResponse) Reset() {
	*x = LoginFinishResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFinishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFinishResponse) ProtoMessage() {}

func (x *LoginFinishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFinishResponse.ProtoReflect.Descriptor instead.
func (*LoginFinishResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginFinishResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginFinishResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginFinishResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type ChangePasswordRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NewKdf              *KdfParams             `protobuf:"bytes,1,opt,name=new_kdf,json=newKdf,proto3" json:"new_kdf,omitempty"`
	NewEncryptedDataKey []byte                 `protobuf:"bytes,2,opt,name=new_encrypted_data_key,json=newEncryptedDataKey,proto3" json:"new_encrypted_data_key,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ChangePasswordRequest) GetNewKdf() *KdfParams {
	if x != nil {
		return x.NewKdf
	}
	return nil
}

func (x *ChangePasswordRequest) GetNewEncryptedDataKey() []byte {
	if x != nil {
		return x.NewEncryptedDataKey
	}
	return nil
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\rgophkeeper.v1\"\xa8\x01\n" +
	"\tKdfParams\x12'\n" +
	"\x03alg\x18\x01 \x01(\x0e2\x15.gophkeeper.v1.KdfAlgR\x03alg\x12\x1b\n" +
	"\ttime_cost\x18\x02 \x01(\rR\btimeCost\x12\x1f\n" +
	"\vmemory_cost\x18\x03 \x01(\rR\n" +
	"memoryCost\x12 \n" +
	"\vparallelism\x18\x04 \x01(\rR\vparallelism\x12\x12\n" +
	"\x04salt\x18\x05 \x01(\fR\x04salt\"\xdf\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12*\n" +
	"\x03kdf\x18\x02 \x01(\v2\x18.gophkeeper.v1.KdfParamsR\x03kdf\x12,\n" +
	"\x12encrypted_data_key\x18\x03 \x01(\fR\x10encryptedDataKey\x12\x19\n" +
	"\bauth_key\x18\x04 \x01(\fR\aauthKey\x12;\n" +
	"\fauth_key_alg\x18\x05 \x01(\x0e2\x19.gophkeeper.v1.AuthKeyAlgR\n" +
	"authKeyAlg\"\x12\n" +
	"\x10RegisterResponse\"P\n" +
	"\x11LoginStartRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\"\xe6\x01\n" +
	"\x12LoginStartResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12*\n" +
	"\x03kdf\x18\x02 \x01(\v2\x18.gophkeeper.v1.KdfParamsR\x03kdf\x12,\n" +
	"\x12encrypted_data_key\x18\x03 \x01(\fR\x10encryptedDataKey\x12;\n" +
	"\fauth_key_alg\x18\x04 \x01(\x0e2\x19.gophkeeper.v1.AuthKeyAlgR\n" +
	"authKeyAlg\x12\x1c\n" +
	"\tchallenge\x18\x05 \x01(\fR\tchallenge\"M\n" +
	"\x12LoginFinishRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\fR\bresponse\"\x85\x01\n" +
	"\x13LoginFinishResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x81\x01\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\"\x7f\n" +
	"\x15ChangePasswordRequest\x121\n" +
	"\anew_kdf\x18\x01 \x01(\v2\x18.gophkeeper.v1.KdfParamsR\x06newKdf\x123\n" +
	"\x16new_encrypted_data_key\x18\x02 \x01(\fR\x13newEncryptedDataKey\"\x18\n" +
	"\x16ChangePasswordResponse*/\n" +
	"\x06KdfAlg\x12\x17\n" +
	"\x13KDF_ALG_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bARGON2ID\x10\x01*L\n" +
	"\n" +
	"AuthKeyAlg\x12\x1c\n" +
	"\x18AUTH_KEY_ALG_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vHMAC_SHA256\x10\x01\x12\x0f\n" +
	"\vHMAC_SHA512\x10\x022\xb1\x03\n" +
	"\vAuthService\x12K\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1f.gophkeeper.v1.RegisterResponse\x12Q\n" +
	"\n" +
	"LoginStart\x12 .gophkeeper.v1.LoginStartRequest\x1a!.gophkeeper.v1.LoginStartResponse\x12T\n" +
	"\vLoginFinish\x12!.gophkeeper.v1.LoginFinishRequest\x1a\".gophkeeper.v1.LoginFinishResponse\x12M\n" +
	"\fRefreshToken\x12\x1d.gophkeeper.v1.RefreshRequest\x1a\x1e.gophkeeper.v1.RefreshResponse\x12]\n" +
	"\x0eChangePassword\x12$.gophkeeper.v1.ChangePasswordRequest\x1a%.gophkeeper.v1.ChangePasswordResponseB\x1aZ\x18gophkeeper/pkg/grpc/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_auth_proto_goTypes = []any{
	(KdfAlg)(0),                    // 0: gophkeeper.v1.KdfAlg
	(AuthKeyAlg)(0),                // 1: gophkeeper.v1.AuthKeyAlg
	(*KdfParams)(nil),              // 2: gophkeeper.v1.KdfParams
	(*RegisterRequest)(nil),        // 3: gophkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 4: gophkeeper.v1.RegisterResponse
	(*LoginStartRequest)(nil),      // 5: gophkeeper.v1.LoginStartRequest
	(*LoginStartResponse)(nil),     // 6: gophkeeper.v1.LoginStartResponse
	(*LoginFinishRequest)(nil),     // 7: gophkeeper.v1.LoginFinishRequest
	(*LoginFinishResponse)(nil),    // 8: gophkeeper.v1.LoginFinishResponse
	(*RefreshRequest)(nil),         // 9: gophkeeper.v1.RefreshRequest
	(*RefreshResponse)(nil),        // 10: gophkeeper.v1.RefreshResponse
	(*ChangePasswordRequest)(nil),  // 11: gophkeeper.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 12: gophkeeper.v1.ChangePasswordResponse
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.KdfParams.alg:type_name -> gophkeeper.v1.KdfAlg
	2,  // 1: gophkeeper.v1.RegisterRequest.kdf:type_name -> gophkeeper.v1.KdfParams
	1,  // 2: gophkeeper.v1.RegisterRequest.auth_key_alg:type_name -> gophkeeper.v1.AuthKeyAlg
	2,  // 3: gophkeeper.v1.LoginStartResponse.kdf:type_name -> gophkeeper.v1.KdfParams
	1,  // 4: gophkeeper.v1.LoginStartResponse.auth_key_alg:type_name -> gophkeeper.v1.AuthKeyAlg
	2,  // 5: gophkeeper.v1.ChangePasswordRequest.new_kdf:type_name -> gophkeeper.v1.KdfParams
	3,  // 6: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.RegisterRequest
	5,  // 7: gophkeeper.v1.AuthService.LoginStart:input_type -> gophkeeper.v1.LoginStartRequest
	7,  // 8: gophkeeper.v1.AuthService.LoginFinish:input_type -> gophkeeper.v1.LoginFinishRequest
	9,  // 9: gophkeeper.v1.AuthService.RefreshToken:input_type -> gophkeeper.v1.RefreshRequest
	11, // 10: gophkeeper.v1.AuthService.ChangePassword:input_type -> gophkeeper.v1.ChangePasswordRequest
	4,  // 11: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.RegisterResponse
	6,  // 12: gophkeeper.v1.AuthService.LoginStart:output_type -> gophkeeper.v1.LoginStartResponse
	8,  // 13: gophkeeper.v1.AuthService.LoginFinish:output_type -> gophkeeper.v1.LoginFinishResponse
	10, // 14: gophkeeper.v1.AuthService.RefreshToken:output_type -> gophkeeper.v1.RefreshResponse
	12, // 15: gophkeeper.v1.AuthService.ChangePassword:output_type -> gophkeeper.v1.ChangePasswordResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		EnumInfos:         file_auth_proto_enumTypes,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
