// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_access_token.sql

package db

import (
	"context"
)

const getAccessToken = `-- name: GetAccessToken :many
SELECT access_token FROM tokens
`

func (q *Queries) GetAccessToken(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAccessToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var access_token string
		if err := rows.Scan(&access_token); err != nil {
			return nil, err
		}
		items = append(items, access_token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
