// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_access_token.sql

package db

import (
	"context"
)

const getAccessToken = `-- name: GetAccessToken :one
SELECT access_token
FROM tokens
WHERE id = 1
`

func (q *Queries) GetAccessToken(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccessToken)
	var access_token string
	err := row.Scan(&access_token)
	return access_token, err
}
