// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: save_access_token.sql

package db

import (
	"context"
)

const saveAccessToken = `-- name: SaveAccessToken :exec
INSERT INTO tokens (id, access_token)
VALUES (1, ?1)
ON CONFLICT(id) DO UPDATE
    SET access_token = excluded.access_token,
        created_at   = excluded.created_at
`

func (q *Queries) SaveAccessToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, saveAccessToken, token)
	return err
}
